### PR TITLE
added diversity parameter to update_topics() function

### PR DESCRIPTION
**Pull request by anubhabdaserrr**
The diversity parameter is a component of topic representation; rather than topic formation (docs -> embeddings -> dimensionality_reduction -> clustering). The update_topics() function should provide the functionality to change the diversity parameter, as and when required. Thanks!

### CODE REVIEW

**Comment by MaartenGr** [comment]
Nice catch, that should definitely be changed! Could you remove the additional whitespace after the diversity parameter and docstrings? Other than that it looks good to me.

**Comment by anubhabdaserrr** [comment]
done!

**Comment by MaartenGr** [comment]
Thanks for the quick update! LGTM, I'll go ahead and merge this now 😄

**Comment by anubhabdaserrr** [comment]
Sorry, I missed out on another parameter - I think top_n_words should also be added, right?

**Pull request merged**
