### PR TITLE
Support custom labels for plots

### PR DESCRIPTION
**Pull request by simonfelding**
I think this is a very useful feature. I added functions to bertopic.py that exports an xlsx sheet with useful data for labeling, but it's not important. Thought it would be nice for usability though.

### CODE REVIEW

**Comment by simonfelding** [comment]
Screenshot 2022-01-25 at 04 58 40

It looks like this now.

**Comment by MaartenGr** [comment]
Thank you for the PR! The changes you made are close to a feature that is on the roadmap, namely creating custom topic representations. As you mentioned, based on the topic representations, users might want to give them a custom name. However, I do think that it would be cleaner to create those custom representations/names within BERTopic instead of the need to pass lists back and forth. That way, they are internally represented and can be used across a variety of functions and more than just the visualizations.

**Comment by simonfelding** [comment]
You could easily modify it to be an internal state instead, but I feel like it's something that's nice to keep seperate from the model itself, since it's something that you might have to change if you realize you did something wrong, and turn on and off easily. For example in my analysis, I had some topics I didn't know how to clearly define, but when I put them in the hierarchial plot it became clear what it was.

I don't really see how you would create the labels in BERTopic without making a complicated analysis and labeling UI, which is something that excel already does really well in my opinion. But it's a good idea to be able to pass the labels to functions like get_topics() and so on! But I think the most powerful analysis features are the visualisations.

But okay, maybe the internal labels could just be an object initialized as an empty list, set like ´topic_model.labels = some_list´ and automatically passed to everything. Then the user gets to figure out how to generate a list of labels without using my handy excel export function. For me it makes sense to keep it seperate though, but I guess I'm just fond of stateless programming. The biggest problem for me with the stateful version would be how to revert the state back to unlabeled without storing the old labels and the custom labels at the same time and having some switching mechanism to turn it on and off. On the other hand, BERTopic could just regenerate the labels if it's an empty list.. I don't like this approach much, maybe you have a better idea.

**Comment by MaartenGr** [comment]
In my experience, users typically want these things to be saved within BERTopic, and this is something I definitely would prefer as well. Ideally, the mapping can be generated by defining a dictionary that maps one topic label to another without the need for excell which might not be available to all users. 

For now, I'll put this on the roadmap to give me some time to think about how this fits best within the current design thinking and choices surrounding BERTopic.

**Pull request closed without merging**
