### PR TITLE
chore: remove obsolete flake8 config

### PR DESCRIPTION
**Pull request by afuetterer**
# What does this PR do?

See https://github.com/MaartenGr/BERTopic/pull/2033#issuecomment-2180892902

## Before submitting
- [ ] This PR fixes a typo or improves the docs (if yes, ignore all other checks!).
- [x] Did you read the [contributor guideline](https://github.com/MaartenGr/BERTopic/blob/master/CONTRIBUTING.md)?
- [ ] Was this discussed/approved via a Github issue? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes (if applicable)?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by MaartenGr** [comment]
Thanks for the PR! I personally like having a bit longer line length to make certain code a bit more readable (like pandas operations). Having said that, I'm okay either way. Do you have a preference having seen the code in this repo?

**Comment by afuetterer** [comment]
I prefer longer line length as well. 80 or 88 like PEP8 or black recommend/enforce are too narrow for me.

I usually prefer 100 or 120. 160 might be too long. What do you think?

**Comment by MaartenGr** [comment]
> I prefer longer line length as well. 80 or 88 like PEP8 or black recommend/enforce are too narrow for me.

Great, I had a feeling I wasn't the only one who liked a bit longer line length here. Let's do 120 since 160 was a bit of a stretch and 100 is too similar to what we have now.

**Comment by MaartenGr** [comment]
Great, LGTM! Should we also re-run ruff to deal with the increased line length or perhaps in a different PR?

**Comment by afuetterer** [comment]
I took the liberty to remove `target-version = "py38"` as well. As it is unneeded, when `requires-python = ">=3.8"` is defined. This is recommended by the ruff docs.

Ref: https://docs.astral.sh/ruff/settings/#target-version

**Comment by afuetterer** [comment]
Re-ran ruff, lint job is passing.

**Comment by MaartenGr** [comment]
@afuetterer I just merged a PR that involves simplifying and improving the zero-shot topic modeling approach. It seems that that merge just created a bunch of conflicts for you, sorry!

**Comment by afuetterer** [comment]
Will fix those soon.

**Comment by afuetterer** [comment]
Rebased, re-ran ruff format on changed files.

**Comment by MaartenGr** [comment]
@afuetterer Great, thanks for the work on this!

**Pull request merged**
