### PR TITLE
Fix hovertemplate indices for LDAviz-like plotting

### PR DESCRIPTION
**Pull request by boscacci**
I had to swap these indices around in order to get "Words: " and "Size: " data to appear in my plots.

### CODE REVIEW

**Comment by MaartenGr** [comment]
Strange that you had to change the indices for "Words" and "Size" as I am already getting the correct values in the example Google Colab session. In what environment with which versions are you getting this issue?

**Comment by boscacci** [comment]
I'm on my local (macOS 10.15.6) in a virtualenv, with pyenv Python 3.8.6:
image

Related packages:
image

I have checked to make sure that my jupyter notebook is using the correct/same venv kernel and site packages.

**Comment by MaartenGr** [comment]
@boscacci Which plotly version are you using? 

This will most likely take some testing since we get different results in our environment. The solution you propose could most likely be correct but I cannot be certain until I test it across different environments and package versions.

**Comment by boscacci** [comment]
Sorry for the delay—I'm on Plotly 4.14.3

**Comment by MaartenGr** [comment]
@boscacci Ah, then that issue is most likely caused by using that Plotly version. If you install BERTopic with `pip install bertopic[visualization]` then it will install a Plotly version below 4.14.3 which should fix the issue.

**Comment by MaartenGr** [comment]
Seeing as this issue was most likely caused by an incompatible version of Plotly, I will close this for now. Please re-open this if using the compatible version of Plotly still gives this issue!

**Comment by boscacci** [comment]
I think yes, likely Plotly version issue, thanks

**Pull request closed without merging**
