### PR TITLE
updated languages list

### PR DESCRIPTION
**Pull request by sam9111**
I got the list from https://www.sbert.net/docs/pretrained_models.html#multi-lingual-models 
Solves #1084

### CODE REVIEW

**Comment by MaartenGr** [comment]
Thank you for the PR. Could you focus on updating the list itself only and keep the style as it was? The other changes are style-dependent and require a different PR.

**Comment by sam9111** [comment]
Yes done! Sorry for that auto-formatting :(

**Comment by MaartenGr** [comment]
No problem, thanks for the PR!

**Comment by MaartenGr** [comment]
Apologies for the late reply. It is merged now, thanks for the PR, greatly appreciated!

**Pull request merged**
