### PR TITLE
'the the' -> 'the'

### PR DESCRIPTION
**Pull request by joshuasundance-swca**
This PR just fixes a typo throughout the codebase.

### CODE REVIEW

**Comment by MaartenGr** [comment]
Thanks, LGTM!

**Comment by MaartenGr** [comment]
I just wanted to merge it but it gave an error that a new commit was pushed. Are there any other upcoming changes or can I go ahead and merge this?

**Comment by joshuasundance-swca** [comment]
> I just wanted to merge it but it gave an error that a new commit was pushed. Are there any other upcoming changes or can I go ahead and merge this?

Oops, sorry! There are no new changes. I just merged the new `master` into this branch.

**Comment by MaartenGr** [comment]
No problem, thanks for the PR!

**Pull request merged**
