### PR TITLE
Fix CUML HDBSCAN predictions by using correct method.

### PR DESCRIPTION
**Pull request by Bougeant**
This fix is intended to fix the bug found here: https://github.com/MaartenGr/BERTopic/discussions/1463

### CODE REVIEW

**Comment by MaartenGr** [comment]
Thanks for the PR! Just to be sure I understand correctly, why is this specific change a solution to the problem? Also, which version of cuML are you using? I believe there were some changes to recent versions that might have fixed this.

**Comment by Bougeant** [comment]
So I think when `func == "membership_vector"`, we should calculate probabilities using `membership_vector(model, embeddings)`, not using `approximate_predict(model, embeddings)` which merely calculates the most relevant cluster and the associated probability. 

I believe that this was just a typo.

**Comment by MaartenGr** [comment]
@Bougeant I believe this relates to https://github.com/MaartenGr/BERTopic/pull/1324 where `approximate_predict` was used for earlier versions of cuML compared to newer versions which do use `membership_vector`. So this was not a typo but merely the functionality that was in v23.03 and lower I believe. If I'm not mistaken, `membership_vector` was introduced in v23.04. 

Perhaps that related PR should be updated and merged instead?

**Comment by Bougeant** [comment]
Oh right, makes sense. In any case, the current implementation does not work since we expect a 2D array but are getting a 2-tuple. #1324 adds some unit tests as well, so that's probably the way to go.

**Pull request closed without merging**
